INSERT INTO "GUEST" (NAME, PASSPORT_NO, EMAIL, PHONE, DATE_OF_BIRTH) 
    VALUES ('James Bond', '007', 'james.bond@queen-service.uk', '0907007007', '1970-01-01');

INSERT INTO "GUEST" (NAME, PASSPORT_NO, EMAIL, PHONE, DATE_OF_BIRTH) 
    VALUES ('James Clark', '123', 'james.clark@superman.com', '0905123123', '1971-01-01');

INSERT INTO "GUEST" (NAME, PASSPORT_NO, EMAIL, PHONE, DATE_OF_BIRTH) 
    VALUES ('Tom Kingsman', '911', 'kingsman@secret-service.uk', '0907911911', '1975-02-01');

INSERT INTO "GUEST" (NAME, PASSPORT_NO, EMAIL, PHONE, DATE_OF_BIRTH) 
    VALUES ('Peter Parkson', '555', 'peter.parkson@spiderman.com', '0901456456', '1977-01-12');

INSERT INTO "ROOM" (NUMBER, CAPACITY , PRICE_PER_NIGHT, BATHROOM , ROOM_TYPE) 
    VALUES ('A001',2,12,0,'STANDARD');

INSERT INTO "ROOM" (NUMBER, CAPACITY , PRICE_PER_NIGHT, BATHROOM , ROOM_TYPE) 
    VALUES ('A012',3,29,1,'SUPERIOR');

INSERT INTO "ROOM" (NUMBER, CAPACITY , PRICE_PER_NIGHT, BATHROOM , ROOM_TYPE) 
    VALUES ('B001',4,38.5,1,'STUDIO');

INSERT INTO "ROOM" (NUMBER, CAPACITY , PRICE_PER_NIGHT, BATHROOM , ROOM_TYPE) 
    VALUES ('B021',1,20,1,'APARTMENT');